// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb1dh2f3aBhqm37higud8evcm1sRMLafE',
    appId: '1:828662072352:web:42457d5024ac274b01e845',
    messagingSenderId: '828662072352',
    projectId: 'flutt3r-f1re-st0r3',
    authDomain: 'flutt3r-f1re-st0r3.firebaseapp.com',
    storageBucket: 'flutt3r-f1re-st0r3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIg73oBNWO5OTJPOQQPNC8gk7GfNCR98',
    appId: '1:828662072352:android:b3ad8c7762cf3e2a01e845',
    messagingSenderId: '828662072352',
    projectId: 'flutt3r-f1re-st0r3',
    storageBucket: 'flutt3r-f1re-st0r3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWwjCwb6E-C2YfGOrmpP4vkiku17jrKGo',
    appId: '1:828662072352:ios:3f16cf255b247d5801e845',
    messagingSenderId: '828662072352',
    projectId: 'flutt3r-f1re-st0r3',
    storageBucket: 'flutt3r-f1re-st0r3.appspot.com',
    iosClientId: '828662072352-a32doo2cs0gkoqdgnkftcmoei3fjeo36.apps.googleusercontent.com',
    iosBundleId: 'me.renatobogar.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWwjCwb6E-C2YfGOrmpP4vkiku17jrKGo',
    appId: '1:828662072352:ios:3f16cf255b247d5801e845',
    messagingSenderId: '828662072352',
    projectId: 'flutt3r-f1re-st0r3',
    storageBucket: 'flutt3r-f1re-st0r3.appspot.com',
    iosClientId: '828662072352-a32doo2cs0gkoqdgnkftcmoei3fjeo36.apps.googleusercontent.com',
    iosBundleId: 'me.renatobogar.app',
  );
}
